type: object
properties:
  nodeSelector:
    type: object
    additionalProperties:
      type: string
    x-kubernetes-preserve-unknown-fields: true
    x-examples:
      - disktype: ssd
    description: |
      The same as in the pods' `spec.nodeSelector` parameter in Kubernetes.

      If the parameter is omitted or `false`, it will be determined [automatically](https://deckhouse.io/products/kubernetes-platform/documentation/v1/#advanced-scheduling).
  tolerations:
    type: array
    items:
      type: object
      properties:
        effect:
          type: string
        key:
          type: string
        operator:
          type: string
        tolerationSeconds:
          type: integer
          format: int64
        value:
          type: string
    x-examples:
      - - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "NoSchedule"
        - key: "key1"
          operator: "Exists"
          effect: "NoSchedule"
    description: |
      The same as in the pods' `spec.tolerations` parameter in Kubernetes;

      If the parameter is omitted or `false`, it will be determined [automatically](https://deckhouse.io/products/kubernetes-platform/documentation/v1/#advanced-scheduling).
  reloadOnCreate:
    type: boolean
    default: true
    description: |
      Rollout the workload in case of creating a ConfigMap or Secret.

      Enabling the parameter will cause the workload to restart not only when changing the corresponding ConfigMap or Secret, but also when creating it.
    x-examples: [true, false]
  reloadOnDelete:
    type: boolean
    default: false
    description: |
      Rollout the workload in case of deleting a ConfigMap or Secret.

      Enabling the parameter will cause the workload to restart when deleting the corresponding ConfigMap or Secret.
    x-examples: [true, false]
  reloadStrategy:
    type: string
    default: Env-vars
    enum:
      - Env-vars
      - Annotations
    description: |
      Strategy to use for triggering reload.

      `Env-vars` - Adds a dummy environment variable to any container referencing the changed resource (e.g., Deployment, StatefulSet, etc.). This forces Kubernetes to perform a rolling update.
      `Annotations` - Adds a pod-reloader.deckhouse.io/last-reloaded-from annotation to the pod template metadata. Ideal for GitOps tools like ArgoCD, as it avoids triggering unwanted sync diffs.
    x-examples: [Env-vars, Annotations]
