type: object
properties:
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` пода Kubernetes.

      Если значение не указано или указано `false`, будет использоваться [автоматика](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    type: array
    description: |
      Структура, аналогичная `spec.tolerations` пода Kubernetes.

      Если значение не указано или указано `false`, будет использоваться [автоматика](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  reloadOnCreate:
    type: boolean
    description: |
      Разрешение перезапуска рабочей нагрузки в случае создания ConfigMap или Secret.

      Включение параметра будет приводить к перезапуску нагрузки не только при изменении соответствующего ConfigMap или Secret, но также и при его создании.
  reloadOnDelete:
    type: boolean
    description: |
      Разрешение перезапуска рабочей нагрузки в случае удаления ConfigMap или Secret.

      Включение параметра будет приводить к перезапуску нагрузки при удалении соответствующего ConfigMap или Secret.
  reloadStrategy:
    type: string
    description: |
      Стратегия для использования при триггере перезапуска.

      `env-vars` - Добавляет dummy переменную окружения для любого контейнера, который использует измененный ресурс (например, Deployment, StatefulSet и т.д.). Это заставляет Kubernetes выполнить rolling update.
      `annotations` - Добавляет pod-reloader.deckhouse.io/last-reloaded-from аннотацию в метаданные шаблона пода. Идеально для GitOps инструментов, таких как ArgoCD, так как избегает триггеров нежелательных синхронизаций.
